server:
  servlet:
    context-path: /eurocup2020
  port: 8123

spring:
  datasource:
    username: masteruser
    password: masteruser_local
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/application_db
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 80
  flyway:
      baselineOnMigrate: true

mybatis:
  mapper-locations: classpath:**/mapper/**/*Mapper.xml

config:
  feature:
  business:
    territory:
      de:
        autowinByOrder: 40
        maxWinners: 10000
        dailyMaxWinners: 250
      hu:
        autowinByOrder: 40
        maxWinners: 10000
        dailyMaxWinners: 250
